# Generated by Django 4.2.8 on 2024-05-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_movie_budget_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
