# Generated by Django 4.2.8 on 2024-05-06 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_movie_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='author',
        ),
    ]
