# Generated by Django 4.2.6 on 2024-05-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_alter_movie_options_alter_movie_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('RUB', 'Ruble'), ('PND', 'Pound'), ('DLR', 'Dollar')], default='DLR', max_length=3),
        ),
    ]
