# Generated by Django 4.2.6 on 2024-05-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_movie_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('RUB', 'Ruble'), ('PND', 'Pound'), ('USD', 'Dollar')], default='USD', max_length=3),
        ),
    ]
