# Generated by Django 4.2.9 on 2024-05-24 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0011_movie_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('gender', models.CharField(choices=[('M', 'мужчина'), ('F', 'женщина')], default='M', max_length=1, verbose_name='Гендер')),
                ('image', models.ImageField(blank=True, default='static/images/not_image.jpeg', null=True, upload_to='static/images/actors')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, verbose_name='URL')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возвраст')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место рождения')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Актера',
                'verbose_name_plural': 'Актеры',
                'db_table': 'actor',
            },
        ),
        migrations.CreateModel(
            name='DressingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveIntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='director',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('NEWRELEASES', 'New Releases'), ('POPULAR', 'popular'), ('CLASSICS', 'classics'), ('COMMON', 'common')], default='COMMON', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movies', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='movie_app.director', verbose_name='Режисер'),
        ),
        migrations.AddField(
            model_name='actor',
            name='dress_room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie_app.dressingroom'),
        ),
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(related_name='movies', to='movie_app.actor', verbose_name='Актер'),
        ),
    ]
