# Generated by Django 4.2.9 on 2024-05-24 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0012_actor_dressingroom_delete_student_director_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
    ]
