# Generated by Django 4.2.9 on 2024-05-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0013_remove_movie_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='currency',
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('NEWRELEASES', 'new_releases'), ('POPULAR', 'popular'), ('CLASSICS', 'classics'), ('COMMON', 'common')], default='COMMON', max_length=50),
        ),
    ]
