# Generated by Django 4.2.9 on 2024-05-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0014_remove_movie_currency_movie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('RUB', 'Ruble'), ('PND', 'Pound'), ('USD', 'Dollar')], default='USD', max_length=3),
        ),
    ]
