# Generated by Django 4.2.9 on 2024-05-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0015_movie_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='dress_room',
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='movie',
            name='image_back',
            field=models.ImageField(blank=True, null=True, upload_to='movies_back', verbose_name='Фон'),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating_imdb',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг IMDb'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
        migrations.DeleteModel(
            name='DressingRoom',
        ),
    ]
