# Generated by Django 4.2.9 on 2024-05-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0016_remove_actor_dress_room_movie_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возврастное ограничение'),
        ),
        migrations.AddField(
            model_name='movie',
            name='category_film',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Категория фильма'),
        ),
        migrations.AddField(
            model_name='movie',
            name='time',
            field=models.FloatField(blank=True, null=True, verbose_name='Время просмотра'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('NEWRELEASES', 'new_releases'), ('POPULAR', 'popular'), ('CLASSICS', 'classics'), ('COMMON', 'common')], default='COMMON', max_length=50, verbose_name='Категория для главной'),
        ),
    ]
