# Generated by Django 4.2.9 on 2024-05-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0017_movie_age_movie_category_film_movie_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category_film',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория фильма'),
        ),
    ]
