# Generated by Django 4.2.9 on 2024-05-30 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0019_movie_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='Рейтинг')),
                ('rating_imdb', models.FloatField(blank=True, null=True, verbose_name='Рейтинг IMDb')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год')),
                ('budget', models.IntegerField(default=100000, verbose_name='Бюджет')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(default='', max_length=200, unique=True, verbose_name='URL')),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('RUB', 'Ruble'), ('PND', 'Pound'), ('USD', 'Dollar')], default='USD', max_length=3)),
                ('category_serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория сериала')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возврастное ограничение')),
                ('time', models.FloatField(blank=True, null=True, verbose_name='Время просмотра')),
                ('image', models.ImageField(blank=True, null=True, upload_to='serials', verbose_name='Изображение')),
                ('image_back', models.ImageField(blank=True, null=True, upload_to='serial_back', verbose_name='Фон')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos', verbose_name='Видео')),
                ('actor', models.ManyToManyField(related_name='serial', to='movie_app.actor', verbose_name='Актер')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serial', to='movie_app.director', verbose_name='Режисер')),
            ],
            options={
                'verbose_name': 'Сериал',
                'verbose_name_plural': 'Сериалы',
                'db_table': 'serial',
            },
        ),
    ]
