# Generated by Django 4.2.9 on 2024-06-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0020_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
        migrations.AddField(
            model_name='movie',
            name='video_hd',
            field=models.FileField(blank=True, null=True, upload_to='videos/1080', verbose_name='Видео 1080'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_high',
            field=models.FileField(blank=True, null=True, upload_to='videos/720', verbose_name='Видео 720'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_medium',
            field=models.FileField(blank=True, null=True, upload_to='videos/480', verbose_name='Видео 480'),
        ),
    ]
